#!/bin/sh

pass=true

# Javascript pre-commit
js_files=$(git diff --cached --name-only | grep ".js$")

for file in ${js_files}; do
    result=$(jshint ${file})
    if [ "$result" != "" ]; then
       echo "${file}: failed jshint\n ${result}"
       pass=false
    else
      echo "${file}: ok"
    fi
done

if ! $pass; then
   echo "Pre-Commit failed, please fix."
   exit 1
fi
